### ISSUE TITLE
Are there any options available to optimize the wasm output file ?

### ISSUE THREAD

**Issue by szagi3891** [IMI-eRnD-Be/wasm-run#13]
After switching to wasm-run, my resulting file takes: 1751865B. Using rollup my resulting file had about 200KB.

Is it possible to configure something to reduce the size of this file ?

**Comment by cecton** [comment]
1MB sounds like a lot, there might be something going on.

wasm-run uses wasm-opt just like wasm-pack does so you shouldn't observe an increase in size between the 2 but I don't really know about rollup.

Please note also that the wasm is optimized only when you use the build command (it's not optimized with the serve command on purpose).

**Comment by szagi3891** [comment]
When I add this option to Cargo.toml:

```
[profile.release]
lto = true
opt-level = 's'
```

Then the size of the resulting wasm file has decreased to 248KB. 
The problem was that I just have to learn to use this tool :) 
Thank you.

**Comment by cecton** [comment]
>  The problem was that I just have to learn to use this tool :)

Don't be too hard on yourself!

I know the documentation is a bit lacking but I just started the project. It's possible I missed a few things here and there. Like the thing you said with the profile is actually not in the `Cargo.toml` of the basic example oops :sweat_smile: will fix it! Thanks for the feedback
