### ISSUE TITLE
Question abuot "cargo run -- build"

### ISSUE THREAD

**Issue by szagi3891** [IMI-eRnD-Be/wasm-run#20]
Is it possible for this mode to generate a smaller version of the resulting wasm file ?

**Comment by cecton** [comment]
Oh you still have issues with the size? How much is it? Is it different from wasm-pack?

There are a few things you can do to help reduce the size of the WASM:

1. `wasm-run` uses `wasm-opt` already. In the latest version, if you disable the default features, it will disable this optimization.
2. In your Cargo.toml you can add the profile:
```
[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
```
3. You can replace the default allocator by `wee_alloc`:
    - In the `Cargo.toml`: https://github.com/cecton/wasm-run-template/blob/83154007f48b0c45ffd26bfd69e198ba45b80cdd/Cargo.toml#L21-L26
    - In the `lib.rs`: https://github.com/cecton/wasm-run-template/blob/83154007f48b0c45ffd26bfd69e198ba45b80cdd/src/lib.rs#L5-L9

**Comment by szagi3891** [comment]
I'm sorry, I was mistaken :)

The question concerns the command:
cargo run -- serve

I would need to generate smaller wasm file in this mode. Otherwise my application is very slow :/

**Comment by cecton** [comment]
You could try using the parameter `--profiling`.

`serve` is meant to be used as development server. How do you use it exactly?

**Comment by szagi3891** [comment]
Great, that's what I need :)

I use it this way:
https://github.com/szagi3891/rust-reactive/blob/master/start.sh

I've used this command before without this add-on `--profiling`.

**Comment by szagi3891** [comment]
It would be worth adding this information about this switch `--profiling` to README.md :)

**Comment by cecton** [comment]
@szagi3891 in development you are not supposed to run an optimized version unless you're trying to profile or test the speed explicitly. This build is slower and therefore annoying to use for development.

If you want to run your frontend in production, you should never use `cargo run -- serve` for that. It is not secured.

**Comment by cecton** [comment]
(I added a note in the README for the next version)
